name: demand-forecasting-agent
channels:
  - https://repo.anaconda.cloud/repo/community
  - defaults
  - https://repo.anaconda.cloud/repo/conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.cloud/repo/rko-demo/pytorch
  - https://repo.anaconda.cloud/repo/main
dependencies:
  - accelerate=1.11.0=pyhcf101f3_0
  - aiodns=3.5.0=py310hca03da5_1
  - aiohappyeyeballs=2.6.1=py310hca03da5_0
  - aiohttp=3.13.2=py310haa24f5a_0
  - aiosignal=1.4.0=py310hca03da5_0
  - ansi2html=1.9.2=py310hca03da5_0
  - anyio=4.10.0=py310hca03da5_0
  - aom=3.9.1=h7bae524_0
  - appnope=0.1.4=py310hca03da5_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py310h254cc4a_0
  - arrow-cpp=21.0.0=h9e9184e_1
  - asttokens=3.0.0=py310hca03da5_0
  - async-lru=2.0.5=py310hca03da5_0
  - async-timeout=5.0.1=py310hca03da5_0
  - attrs=25.4.0=py310hca03da5_2
  - aws-c-auth=0.9.0=h79febb2_2
  - aws-c-cal=0.9.2=h79febb2_1
  - aws-c-common=0.12.4=h79febb2_0
  - aws-c-compression=0.3.1=h79febb2_2
  - aws-c-event-stream=0.5.6=h79febb2_0
  - aws-c-http=0.10.4=h79febb2_0
  - aws-c-io=0.21.4=h79febb2_0
  - aws-c-mqtt=0.13.3=h387b88a_0
  - aws-c-s3=0.8.7=h79febb2_0
  - aws-c-sdkutils=0.2.4=h79febb2_1
  - aws-checksums=0.2.7=h79febb2_1
  - aws-crt-cpp=0.34.0=hee39554_0
  - aws-sdk-cpp=1.11.638=h35fa3df_0
  - babel=2.16.0=py310hca03da5_0
  - beautifulsoup4=4.13.5=py310hca03da5_0
  - blas=1.0=openblas
  - bleach=6.2.0=py310hca03da5_0
  - blinker=1.9.0=py310hca03da5_0
  - boto3=1.40.54=py310hca03da5_0
  - botocore=1.40.54=py310hca03da5_0
  - bottleneck=1.4.2=py310h03d0aa3_1
  - brotli-python=1.2.0=py310h5b255a4_0
  - brotlicffi=1.1.0.0=py310h50f4ffc_0
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.11.4=hca03da5_0
  - certifi=2025.11.12=py310hca03da5_0
  - cffi=2.0.0=py310h73c2a22_1
  - charset-normalizer=3.4.4=py310hca03da5_0
  - click=8.2.1=py310hca03da5_0
  - comm=0.2.3=py310hca03da5_0
  - contourpy=1.3.1=py310h48ca7d4_0
  - cpuonly=2.0=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dash=2.14.2=py310hca03da5_0
  - dash-bootstrap-components=2.0.3=pyhd8ed1ab_0
  - datasets=3.3.2=py310hca03da5_0
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.8.16=py310h50f4ffc_1
  - decorator=5.2.1=py310hca03da5_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.3.8=py310hca03da5_0
  - exceptiongroup=1.3.0=py310hca03da5_0
  - executing=2.2.1=py310hca03da5_0
  - expat=2.7.3=h982b769_0
  - filelock=3.20.0=py310hca03da5_0
  - flask=3.0.3=py310hca03da5_0
  - flask-compress=1.17=py310hca03da5_0
  - fonttools=4.60.1=py310h254cc4a_0
  - freetype=2.14.1=hce30654_0
  - frozenlist=1.8.0=py310h50f4ffc_0
  - fsspec=2024.12.0=py310hca03da5_0
  - gettext=0.21.0=hbdbcc25_2
  - gflags=2.2.2=h313beb8_1
  - giflib=5.2.2=h80987f9_0
  - glog=0.5.0=h313beb8_1
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py310h5c1b81f_0
  - h11=0.16.0=py310hca03da5_1
  - hatchling=1.27.0=py310hca03da5_1
  - hf-xet=1.1.8=py310h8cd5084_0
  - httpcore=1.0.9=py310hca03da5_0
  - httpx=0.28.1=py310hca03da5_1
  - huggingface_hub=0.34.4=py310hca03da5_0
  - icu=73.1=h313beb8_0
  - idna=3.11=py310hca03da5_0
  - importlib-metadata=8.5.0=py310hca03da5_0
  - ipykernel=6.31.0=py310h7eb115d_0
  - ipython=8.30.0=py310hca03da5_0
  - ipython_pygments_lexers=1.1.1=py310hca03da5_0
  - ipywidgets=8.1.7=py310hca03da5_0
  - itsdangerous=2.2.0=py310hca03da5_0
  - jansson=2.14=h80987f9_1
  - jedi=0.19.2=py310hca03da5_0
  - jinja2=3.1.6=py310hca03da5_0
  - jmespath=1.0.1=py310hca03da5_0
  - joblib=1.5.2=py310hca03da5_0
  - json5=0.12.1=py310hca03da5_0
  - jsonschema=4.25.0=py310hca03da5_1
  - jsonschema-specifications=2025.9.1=py310hca03da5_0
  - jupyter=1.1.1=py310hca03da5_0
  - jupyter-lsp=2.2.5=py310hca03da5_0
  - jupyter_client=8.6.3=py310hca03da5_1
  - jupyter_console=6.6.3=py310hca03da5_0
  - jupyter_core=5.8.1=py310hca03da5_0
  - jupyter_events=0.12.0=py310hca03da5_0
  - jupyter_server=2.16.0=py310hca03da5_0
  - jupyter_server_terminals=0.5.3=py310hca03da5_0
  - jupyterlab=4.4.7=py310hca03da5_0
  - jupyterlab_pygments=0.3.0=py310hca03da5_0
  - jupyterlab_server=2.28.0=py310hca03da5_0
  - jupyterlab_widgets=3.0.15=py310hca03da5_0
  - kiwisolver=1.4.8=py310h313beb8_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libavif16=1.3.0=hb06b76e_2
  - libbrotlicommon=1.0.9=h80987f9_9
  - libbrotlidec=1.0.9=h80987f9_9
  - libbrotlienc=1.0.9=h80987f9_9
  - libcurl=8.16.0=h01d3526_0
  - libcxx=20.1.8=hd7fd590_1
  - libde265=1.0.15=h2ffa867_0
  - libdeflate=1.22=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libgrpc=1.71.0=h62f6fdd_0
  - libheif=1.19.7=gpl_h79e6334_100
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.8=h9681e36_0
  - libjpeg-turbo=3.1.2=h3afaa1a_0
  - libnghttp2=1.67.1=h8189af8_0
  - libopenblas=0.3.30=hf2bb037_2
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.50=h5c318fc_0
  - libprotobuf=5.29.3=h14f15fd_1
  - libre2-11=2024.07.02=h313beb8_0
  - libsodium=1.0.20=h897f8a9_0
  - libsqlite=3.51.0=h9a5124b_0
  - libssh2=1.11.1=h3e2b118_0
  - libthrift=0.22.0=hbe873a3_0
  - libtiff=4.7.0=hfce79cd_1
  - libtorch=2.7.0=cpu_openblas_h7dbb27e_0
  - libunistring=1.3=h1799b2a_0
  - libuv=1.48.0=h80987f9_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=h3fc13f7_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py310h80987f9_0
  - matplotlib=3.10.6=py310hca03da5_1
  - matplotlib-base=3.10.6=py310h37b8ce2_1
  - matplotlib-inline=0.2.1=py310hca03da5_0
  - mistune=3.1.2=py310hca03da5_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py310hca03da5_0
  - multidict=6.7.0=py310h254cc4a_0
  - multiprocess=0.70.15=py310hca03da5_0
  - narwhals=2.7.0=py310hca03da5_0
  - nbclient=0.10.2=py310hca03da5_0
  - nbconvert=7.16.6=py310hca03da5_0
  - nbconvert-core=7.16.6=py310hca03da5_0
  - nbconvert-pandoc=7.16.6=py310hca03da5_0
  - nbformat=5.10.4=py310hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py310hca03da5_0
  - networkx=3.4.2=py310hca03da5_0
  - nomkl=3.0=0
  - notebook=7.4.5=py310hca03da5_0
  - notebook-shim=0.2.4=py310hca03da5_0
  - numexpr=2.14.1=py310h5fbe615_0
  - numpy=2.2.5=py310h40d09ce_2
  - numpy-base=2.2.5=py310h855c928_2
  - openjpeg=2.5.4=h959fc53_1
  - openssl=3.0.18=h9b4081a_0
  - opentelemetry-api=1.37.0=py310hca03da5_0
  - orc=2.2.0=hec253e6_0
  - overrides=7.7.0=py310hca03da5_0
  - packaging=25.0=py310hca03da5_1
  - pandas=2.3.3=py310h3f644e9_1
  - pandoc=3.8=hca03da5_0
  - pandocfilters=1.5.1=py310hca03da5_0
  - parso=0.8.5=py310hca03da5_0
  - pathspec=0.12.1=py310hca03da5_1
  - pexpect=4.9.0=py310hca03da5_1
  - pillow=11.3.0=py310h5de80a5_3
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=py310hca03da5_0
  - plotly=6.3.0=py310hd096484_0
  - pluggy=1.5.0=py310hca03da5_0
  - prometheus_client=0.21.1=py310hca03da5_0
  - prompt-toolkit=3.0.52=py310hca03da5_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - propcache=0.3.1=py310h80987f9_0
  - prophet=1.1.5=py310h48ca7d4_0
  - psutil=7.0.0=py310haa24f5a_1
  - pthread-stubs=0.3=h1a28f6b_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py310hca03da5_0
  - pyarrow=21.0.0=py310hc6ded6b_0
  - pycares=4.10.0=py310h091efcb_0
  - pycparser=2.23=py310hca03da5_0
  - pygments=2.19.2=py310hca03da5_0
  - pyparsing=3.2.0=py310hca03da5_0
  - pysocks=1.7.1=py310hca03da5_1
  - python=3.10.9=h3ba56d0_0_cpython
  - python-dateutil=2.9.0post0=py310hca03da5_2
  - python-dotenv=1.1.0=py310hca03da5_0
  - python-fastjsonschema=2.21.2=py310hca03da5_0
  - python-json-logger=3.2.1=py310hca03da5_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py310h80987f9_0
  - python_abi=3.10=1_cp310
  - pytorch=2.7.0=cpu_openblas_py310h18626dc_0
  - pytorch-mutex=1.0=cpu
  - pytz=2025.2=py310hca03da5_0
  - pyyaml=6.0.3=py310h091b9d3_0
  - pyzmq=27.1.0=py310h5a8c52c_1
  - qtconsole=5.7.0=py310hca03da5_0
  - qtpy=2.4.3=py310hca03da5_0
  - rav1e=0.7.1=h0716509_3
  - re2=2024.07.02=h48ca7d4_0
  - readline=8.3=h0b18652_0
  - referencing=0.37.0=py310hca03da5_0
  - regex=2025.9.1=py310h254cc4a_0
  - requests=2.32.5=py310hca03da5_1
  - retrying=1.3.3=pyhd3eb1b0_2
  - rfc3339-validator=0.1.4=py310hca03da5_0
  - rfc3986-validator=0.1.1=py310hca03da5_0
  - rpds-py=0.28.0=py310h931abed_0
  - s3transfer=0.14.0=py310hca03da5_0
  - safetensors=0.6.2=py310h931abed_0
  - scheduler=0.8.8=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py310hc6ded6b_0
  - scipy=1.15.3=py310h132fc3c_1
  - seaborn=0.13.2=py310hca03da5_3
  - send2trash=1.8.2=py310hca03da5_1
  - setuptools=80.9.0=py310hca03da5_0
  - six=1.17.0=py310hca03da5_0
  - sleef=3.5.1=h80987f9_2
  - snappy=1.2.1=h313beb8_0
  - sniffio=1.3.0=py310hca03da5_0
  - soupsieve=2.5=py310hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - stack_data=0.6.3=py310hca03da5_0
  - statsmodels=0.14.5=py310h12bd487_0
  - svt-av1=3.1.2=h12ba402_0
  - sympy=1.14.0=py310hca03da5_0
  - terminado=0.18.1=py310hca03da5_0
  - threadpoolctl=3.5.0=py310h33ce5c2_0
  - tinycss2=1.4.0=py310hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - tokenizers=0.22.1=py310h99e1e97_0
  - tomli=2.2.1=py310hca03da5_0
  - torchvision=0.22.0=cpu_py310_he963e65_0
  - torchvision-extra-decoders=0.0.2=py310h74cdeaf_3
  - tornado=6.5.1=py310h80987f9_0
  - tqdm=4.67.1=py310h7eb115d_1
  - traitlets=5.14.3=py310hca03da5_0
  - transformers=4.57.1=pyhd8ed1ab_0
  - trove-classifiers=2025.5.9.12=py310hca03da5_0
  - typeguard=4.4.4=py310hca03da5_0
  - typing-extensions=4.15.0=py310hca03da5_0
  - typing_extensions=4.15.0=py310hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py310hca03da5_0
  - utf8proc=2.6.1=h80987f9_1
  - uvloop=0.22.1=py310h8e34c70_1
  - wcwidth=0.2.13=py310hca03da5_0
  - webencodings=0.5.1=py310hca03da5_1
  - websocket-client=1.8.0=py310hca03da5_0
  - werkzeug=3.0.6=py310hca03da5_0
  - wheel=0.45.1=py310hca03da5_0
  - widgetsnbextension=4.0.14=py310hca03da5_0
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.12=h3fc13f7_0
  - xorg-libxdmcp=1.1.5=h3fc13f7_0
  - xxhash=0.8.0=h1a28f6b_3
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - yarl=1.22.0=py310haa24f5a_0
  - zeromq=4.3.5=h2c7f8f0_1
  - zipp=3.21.0=py310hca03da5_0
  - zlib=1.3.1=h5f15de7_0
  - zstandard=0.24.0=py310hbc14757_0
  - zstd=1.5.7=h817c040_0
prefix: /Users/smonroe/miniconda3/envs/demand-forecasting-agent
